apiVersion: "apiregistration.k8s.io/v1"
kind: "APIService"
metadata:
  name: "v1beta1.metrics.k8s.io"
  namespace: "kube-system"
spec:
  service:
    name: "metrics-server"
    namespace: "kube-system"
  group: "metrics.k8s.io"
  groupPriorityMinimum: 100
  version: "v1beta1"
  versionPriority: 100
  insecureSkipTLSVerify: true
