apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      deployment: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        deployment: metrics-server
    spec:
      containers:
        - name: metrics-server
          image: docker.io/ricardbejarano/metrics-server:0.3.5-musl
          args:
            - --logtostderr
            - --secure-port=8443
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      serviceAccountName: metrics-server
