apiVersion: "v1"
kind: "Service"
metadata:
  name: "metrics-server"
  namespace: "kube-system"
spec:
  selector:
    deployment: "metrics-server"
  ports:
    - name: "443tcp"
      port: 443
      targetPort: 8443
      protocol: "TCP"
